"""What a tool is, and the registry that turns model output into a real function call.

Two methods here bridge "the model said something" and "something happened":

    schemas()   — describes the available tools to the model, in OpenAI tool format
    dispatch()  — takes one ToolCall and actually runs it

Everything else in this file exists to make `dispatch` safe against untrusted input,
because every argument it receives was generated by a language model and may be wrong in
any way: unknown tool name, malformed JSON, missing arguments, or arguments that make the
tool crash. None of those may end the run — each becomes an observation the model reads.
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass
from typing import Any, Protocol

from agentfix.llm.types import INVALID_ARGUMENTS, ToolCall

# Every byte a tool returns is a byte of context the model must re-read on every later
# turn, so tool output is capped. These limits are the difference between a run that fits
# in a 16k context and one that silently truncates mid-history.
MAX_TOOL_OUTPUT_CHARS = 2000
MAX_FILE_READ_CHARS = 4000  # a file read gets a larger budget than a directory listing
TRUNCATION_MARKER = "\n[...truncated]"


def truncate(text: str, limit: int = MAX_TOOL_OUTPUT_CHARS) -> str:
    """Cap `text`, leaving a visible marker so the model knows it did not see everything."""
    if len(text) <= limit:
        return text
    return text[:limit] + TRUNCATION_MARKER


@dataclass(frozen=True)
class ToolResult:
    """What a tool can know: did it work, and what should the model be told.

    Deliberately does NOT carry the model's call id. A tool like `ReadFileTool` knows
    whether the read succeeded; it has no idea what id the model used, and no reason to.
    That belongs to `ToolOutcome` below.
    """

    ok: bool  # currently informational — the model is told success or failure via `content`
    content: str  # the observation text the model will read


@dataclass(frozen=True)
class ToolOutcome:
    """A ToolResult plus the protocol identity needed to send it back to the model.

    The split from `ToolResult` is what lets `dispatch` fabricate results for calls that
    never reached a tool — unknown tool, bad JSON, missing arguments, tool crash. In each
    of those cases `dispatch` has the call id in hand and no tool ran, so it constructs a
    ToolResult itself and wraps it here. The loop cannot tell the difference, which is
    exactly the point: every failure mode looks like a normal observation.
    """

    call_id: str
    name: str
    result: ToolResult

    def as_message(self) -> dict[str, Any]:
        """Render as a chat message the model can match to its own request.

        The `tool_call_id` is required by the API: when a model issues several calls in one
        turn, this is how it pairs each answer with the right question. This method lives
        here rather than on ToolResult because ToolResult has no id to put in it.
        """
        return {
            "role": "tool",
            "tool_call_id": self.call_id,
            "name": self.name,
            "content": self.result.content,
        }


class Tool(Protocol):
    """The shape every tool has. See `LLMClient` in llm/types.py for how Protocol works.

    The three data members become the model's description of the tool, via `schemas()`
    below. They are class attributes on each tool (assigned in the class body, shared by
    all instances) because they describe the tool *type* and never vary per instance,
    while things like the workspace root are per-instance and set in `__init__`.
    """

    name: str
    description: str
    parameters: dict[str, Any]  # JSON Schema; `dispatch` reads its "required" list

    # `*args: Any, **kwargs: Any` is a special construct — the typing spec calls it a
    # "gradual callable form" — meaning this signature is compatible with ANY concrete
    # signature. It is needed because each tool declares its own named parameters
    # (`run(self)`, `run(self, path)`, `run(self, path, content)`) and there is no single
    # parameter list that describes all three.
    #
    # A `**kwargs`-only declaration looks equivalent and is not: it would require an
    # implementation that accepts *arbitrary* keywords, which no tool does, so every tool
    # in the repo would fail the check. (That was a real bug here until mypy was added.)
    # mypy and pyright both implement this rule; PyCharm's own inspector does not, and may
    # show a false "expected Sequence[Tool]" warning at the ToolRegistry call in runner.py.
    def run(self, *args: Any, **kwargs: Any) -> ToolResult: ...


class ToolRegistry:
    """Holds the tools, describes them to the model, and dispatches the model's calls."""

    def __init__(self, tools: Sequence[Tool]) -> None:
        # `Sequence[Tool]` accepts a list or a tuple, and having no `.append` also signals
        # that this constructor will not mutate what you pass in. The general rule: accept
        # the widest type you can use, store the most specific one you need.
        #
        # Stored as a dict keyed on name because `dispatch` looks tools up by name on every
        # single call — O(1) instead of scanning a list. Note this means two tools with the
        # same name would silently collapse into one.
        self._tools: dict[str, Tool] = {tool.name: tool for tool in tools}

    def schemas(self) -> list[dict[str, Any]]:
        """The tool list in OpenAI tool-calling format, sent on every turn.

        This is the model's *only* description of what it can do. `system_prompt` in
        agent/loop.py also derives the tool names from this, so adding a tool to the
        registry updates both the schema and the prompt with no other edits.
        """
        return [
            {
                "type": "function",
                "function": {
                    "name": tool.name,
                    "description": tool.description,
                    "parameters": tool.parameters,
                },
            }
            for tool in self._tools.values()
        ]

    def get(self, name: str) -> Tool:
        """Look up a tool by name. Raises KeyError — for internal use, not model input."""
        return self._tools[name]

    def dispatch(self, call: ToolCall) -> ToolOutcome:
        """Run one model-requested call, converting every possible failure into an observation.

        This is the trust boundary for model output. Four of the five paths below return
        without any tool having run. None of them raise, because an exception here would
        end the run, while an observation gives the model a chance to correct itself — and
        recovering from its own mistakes is most of what an agent does.
        """
        # 1. Hallucinated tool name. Listing what does exist turns a dead end into a hint.
        tool = self._tools.get(call.name)
        if tool is None:
            available = ", ".join(sorted(self._tools))
            return ToolOutcome(
                call.id,
                call.name,
                ToolResult(False, f"No such tool: {call.name}. Available tools: {available}"),
            )

        # 2. The arguments were not valid JSON (see INVALID_ARGUMENTS in llm/types.py).
        # Naming the real problem matters: "missing argument: path" would be misleading,
        # because the model probably did send a path — inside broken JSON.
        if INVALID_ARGUMENTS in call.arguments:
            return ToolOutcome(
                call.id,
                call.name,
                ToolResult(
                    False,
                    f"Your arguments for {call.name} were not valid JSON, so nothing ran. "
                    "Send the call again with a single well-formed JSON object.",
                ),
            )

        # 3. Valid JSON, but a required argument is absent. Checked against the tool's own
        # declared schema, so this stays correct as tools are added or changed.
        missing = [key for key in tool.parameters.get("required", []) if key not in call.arguments]
        if missing:
            return ToolOutcome(
                call.id,
                call.name,
                ToolResult(False, f"Missing required argument(s): {', '.join(missing)}"),
            )

        # 4. Actually run it. The `**` here is *unpacking*: it spreads the arguments dict
        # into keyword arguments, so {"path": "a.py"} becomes run(path="a.py"). This is the
        # exact point where model-generated JSON becomes a real Python call, and the reason
        # each tool can declare named, typed parameters instead of digging through a dict.
        try:
            result = tool.run(**call.arguments)
        except Exception as error:  # a tool crash must not kill the run
            # Broad on purpose. A tool can raise anything — including TypeError if the model
            # sent an unexpected keyword that slipped past the checks above — and the model
            # can often recover if simply told what went wrong.
            return ToolOutcome(
                call.id,
                call.name,
                ToolResult(False, f"Tool raised {type(error).__name__}: {error}"),
            )

        # 5. Success: pair the tool's own result with the call id it answers.
        return ToolOutcome(call.id, call.name, result)
